### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by willscott** [citizenlab/test-lists#11]
Tracking issue for development of an API for extracting URLs for specific categories and/or countries.

**Comment by hellais** [comment]
OONI Runs an API of this sorts which is used by OONI Probes: https://orchestrate.ooni.io/api/v1/test-list/urls?country_code=IT&category_codes=NEWS.

The sorting is randomised and it's synched automatically with this repo every hour. I think it's out of scope for the test-lists repo to have such a canonical API.
