### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by irl** [citizenlab/test-lists#111]
Hi, I'm adding support for using these lists in https://github.com/irl/hellfire which will end up in https://pathspider.net eventually.

As an academic, I may need to cite the lists. Is there a way in which you'd like that to be done?

Thanks,

**Comment by sneft** [comment]
Great, thanks for contributing. To be honest I don't know the standard practice for citing Github repos - is there an accepted practice? We (at the Citizen Lab) are owners of this particular repo so that might be simplest, but I also don't want to claim credit for what is a collaborative project.

**Comment by willscott** [comment]
Citing the web resource is probably sufficient:
```bibtex
@misc{testlist,
  title={URL testing lists intended for discovering website censorship},
  author={Citizen Lab and Others},
  year={2014},
  url={https://github.com/citizenlab/test-lists},
  note={\href{https://github.com/citizenlab/test-lists}{https://github.com/citizenlab/test-lists}}
}
```

**Comment by hellais** [comment]
We should probably add the preferred citation method to the Readme. @willscott would you like to submit a PR with that?

**Comment by hellais** [comment]
This is done.
