### ISSUE TITLE
Blocked Websites in South Korea

### ISSUE THREAD

**Issue by Nutomic** [citizenlab/test-lists#129]
Here are some websites that are blocked by the South Korean government:

http://www.kcna.kp/ (North Korean website)
http://www.marijuanatravels.com/ (Drugs)

Blocked websites are redirected to http://warning.or.kr/

**Comment by jakubd** [comment]
Thanks for the suggestions! I added the URLs with this PR.

**Comment by hellais** [comment]
Merged
