### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by marek22k** [citizenlab/test-lists#1360]
Hello,

many projects have decided to rename the Branch "Master" to "Main" because of the language. Maybe OONI / Citizen Lab might do the same?

**Comment by hellais** [comment]
Hi @marek22k, thanks so much for reaching out and sharing this suggestion. Unfortunately changing the default branch name to main is not such a trivial change as you might think. Us and potentially many other third party researchers use this repository as part of their tooling and make the assumption that the default branch name is the "master" branch.

As such, changing the default will break ours and potentially other integrations, so it's not something that we can easily do.

For all new projects we do start them with `main` as the default branch name, but the work required to change existing ones is just too much that we cannot afford to do it.
