### ISSUE TITLE
Make list of government issued blocklists

### ISSUE THREAD

**Issue by hellais** [citizenlab/test-lists#16]
# Add links into the comments below!

Are you aware of a government issued blocklist that is available for download?

Then add a link pointing to where it can be downloaded (even better if you specify if it's legal or not to mirror/publish it) and what country to applies to.

If you want to be :+1: :100: then you should write the parser code and submit a pull request ;)

**Comment by jakubd** [comment]
Two that jump out in my mind are:

Indonesia - http://trustpositif.kominfo.go.id/
Russia - http://eais.rkn.gov.ru/  or the less official but very reliable antizapret

Some countries will need to be scraped often so we can easily see when URLs are added/removed.  We would need to stage a machine to check and update the repo when this happens.

**Comment by arglebarf** [comment]
There's http://engelliweb.com/ for Turkey. 

Not a gov site, but a volunteer.

**Comment by graphiclunarkid** [comment]
There's a bunch of information for the UK, and limited information on other countries, on the Error 451 wiki: http://wiki.451unavailable.org.uk/wiki/Main_Page

It'd be wonderful if you felt like updating the site with the information from this thread too :smile:

**Comment by hellais** [comment]
@arglebarf @graphiclunarkid could you submit a PR with the URLs inside of that list?

You can see how to properly format and structure the parsers in this directory: https://github.com/citizenlab/test-lists/tree/master/lib/lists/official/it

**Comment by darkk** [comment]
RU: http://reestr.rublacklist.net/api/current (that's unofficial API)

**Comment by kaerumy** [comment]
List of escort sites blocked in india:

http://cis-india.org/internet-governance/blog/list-of-blocked-escort-service-websites

```
www.sterlingbioscience.com
rawpoint.biz
www.onemillionbabes.com
www.mumbaihotcollection.in
simranoberoi.in
rubinakapoor.biz
talita.biz
www.mumbaiescortsagency.net
www.mumbaifunclubs.com
www.alishajain.co.in
www.ankitatalwar.co.in
https://www.jennyarora.ind.in
www.riya-kapoor.com
shneha.in
missinimi.in
www.mumbaiglamour.in
kalyn.in
www.saumyagiri.co.in/city/mumbai/
bookerotic.com
www.divyamalik.in
www.suhanisharma.co.in
www.ruhi.biz
umbaiqueens.in
www.aliyaghosh.com
priyasen.in
www.highprofilemumbaiescorts.co.in
charmingmumbai.com
www.poojamehata.in
kiiran.in/
mansikher.in
www.newmumbaiescorts.in
www.mumbaifunclubs.com
www.punarbas.in
www.discreetbabes.in
www.alisharoy.in
www.arpitarai.in
www.nidhipatel.in
navimumbailescort.com
www.zoyaescorts.com
www.juhioberoi.in
shoniya.in
panchibora.in
rehu.in
www.nehaanand.com
www.aditiray.co.in
www.rakhibajaj.in
www.alianoidaescorts.in
www.sobiya.in
www.alishaparul.in
mumbai-escorts.leathercurrency.com
ankita-ahuja.in
www.yamika.in
mumbailescort.co
www.ranjika.in
www.aditiray.com
www.alinamumbailescort.in
www.sonikaa.com/services/
riyamodel.in
mumbai-escorts.info
soonam.in
www.sejalthakkar.com
www.yomika-tandon.in
www.asika.in
www.siyasharma.org/
www.rubikamathur.in
www.mumbaiescortslady.com
www.sexyshe.in
www.indepandentescorts.com
www.saanvichopra.co.in
www.goswamipatel.in
ojaloberoi.in
www.naincy.in
www.sonyamehra.com
www.pinkgrapes.in
anjalitomar.in/
www.nishakohli.com/
sagentia.co.in
mumbai.vivastreet.co.in/escort+mumbai
www.deseescortgirls.in
guides.wonobo.com/mumbai/mumbai-escorts-service/.4299
jasmineescorts.com
www.shalinisethi.com
www.highclassmumbailescort.com
www.vipescortsinmumbai.com
www.mumbaiescorts69.co.in
monikabas.co.in
www.riyasehgal.com
onlycelebrity.in
www.greatmumbaiescorts.com/escort-service-mumbai.html
www.aishamumbailescort.com
www.jennydsouzaescort.com
www.desifun.in
www.siyaescort.co.in
masti—escort.in
www.sofya.in
www.mumbaiwali.in/navi-mumbai-escort-service.php
www.mumbaiwali.in
www.calldaina.com
www.mumbaiescortsservice.co.in
www.escortsgirlsinmumbai.com
www.passionmumbai.escorts.com
www.nehakapoor.in
meerakapoor.com
www.dianamumbaiescorts.net .in
www.allmumbailescort.in
www.rakhiarora.in
www.ritikasingh.com
www.rekhapatil.com
www.mumbaidolls.com
www.piapandey.com
www.mumbaicuteescorts.in
www.mumbaiescortssevice.com
www.onlycelebrity.com
www.meetescortservice.com
onlyoneescorts.com
simirai.org
www.riyamumbaiescorts.in
www.neharana.in
www.tanyaroy.com
www.mumbaihiprofilegirls.in
www.sexyescortsmumbai.in
www.sexymumbai.escorts.com
www.four-seasons—escort.in
www.mumbaiescortsgirl.com
www.vdreamescorts.com
www.passionatemumbaiescorts.in
www.payalmalhotra.in
www.shrutisinha.com
www.juliemumbaiescorts.com
www.indiasexservices.com/mumbai.html
www.mumbai-escorts.co.in
www.aliyamumbaiescorts.net.in
shivaniarora.co.in/escort–service-mumbai.html
www.pinkisingh.com
soyam.in
www.arpitaray.com
www.localescorts.in
www.jennifermumbaiescorts.com
www.yanaroy.com
escorts18.in/mumbai—escorts.html
www.tinamumbaiescorts.com
www.mumbaijannatescorts.com
www.deepikaroy.com
www.nancy.co.in
www.pearlpatel.in
30minsmumbaiescorts.in
www.datinghopes.com
https://www.riyaroy.com/services.html
www.sonalikajain.com
www.zainakapoor.co.in
kavyajain.in
www.kinnu.co.in
exmumbai.in/
www.mansimathur.in/pinkyagarwal
exmumbai.in
www.mansimathur.in/pinkyagarwal
www.devikabatra.in
katlin.in
riyaverma.in
escortsinindia.co/
www.snehamumbaiescorts.in
shimi.in
www.mumbaiescortsforu.com/about
www.chetnagaur.co.in/chetna-gaur.html
www.escortspoint.in
www.rupalikakkar.in
www.hemangisinha.co.in
1escorts.in/location/mumbai.html
www.salini.in/navi-mumbai-independent—escort-service.php
www.salini.in/navi-mumbai-independent-escort-service.php
www.mumbaibella.in
mohitescortservicesmumbai.com
www.anchu.in
www.aliyaroy.co.in
jaanu.co.in/mumbai-escorts-service-call-girls.html
www.andyverma.com
dreams-come-true.biz
feel–better.biz
jellyroll.biz
dreamgirlmumbai.com
role-play.biz
mansi—mathur.com
www.zarinmumbaiescorts.com
mymumbai.escortss.com
www.goldentouchescorts.com
www.mumbaipassion.biz
ishitamalhotra.com
happy-ending.biz
juicylips.biz
www.escortsmumbai.name
www.kirstygbasai.net
www.hiremumbaiescorts.com
www.meeraescorts.com/mumbai-escorts.php
3–5–7star.biz
www.pranjaltiwari.com
www.richagupta.biz
way2heaven.biz
piya.co/
pinkflowers.info
www.beautifulmumbaiescorts.com
www.bestescortsinmumbai.com/charges-html
www.mumbaiescorts.me
www.tanikatondon.com
www.escortsinmumbai.biz
www.escortgirlmumbai.com
www.mumbaicallgrils.com
www.quickescort4u.com
www.mayamalhotra.com
www.legal-escort.com
escortsbaba.com/mumbai-escorts.html
rupa.biz
www.mumbaiescorts.agency/erotic-service-mumbai.html
www.escortscelebrity.com
www.independentescortservicemumbai.com/mumbai%20escort%20servi..
garimachopra.com
kajalgupta.biz
lipkiss.site
aanu.in
bombayescort.in
hotkiran.co.in
khushikapoor.in
joyapatel.in
rici.in
aaditi.in
andheriescorts.org.in
www.jiyapatel.in
spicymumbai.in
rimpyarora.in
lovemaking.co.in
riyadubey.co.in
escortservicesmumbai.in
mumbaiescorts.co.in
midnightprincess.in/
vashiescorts.co.in/
angee.in/
www.rozakhan.in/
www.mumbaiescortsvilla.in/
kylie.co.in/
escortservicemumbai.co.in
```

**Comment by arglebarf** [comment]
Thinking about this, this does not seem like the right approach. These lists should simply be merged with the relevant country list. possibly using the 'source' and 'notes' fields to indicate that these are from 'government issued blacklists'.

**Comment by farinluck869** [comment]
**[Mumbai Escorts](http://www.farinluck.com/) - Enjoy the Company of Hot and VIP Models**
Mumbai Escorts services of FarinLuck Escorts Services is the only way to get together on bed with really hot and gorgeous models that is always a dream to every one. these escorts are always special and exclusive for specific persons. http://www.farinluck.com/

**Comment by ak506935** [comment]
I'm Single Girl Ansha Khan http://anshaescorts.com/gallery.html offering night shift [Goa escorts service](http://anshaescorts.com/), Booking Advance before landed your flight and I'm waiting top class Hotel.
Personal Website : http://anshaescorts.com/
Our Sister Partner Website
http://sohaescorts.com/
http://sohaescorts.com/services.html

**Comment by peehusinha321** [comment]
Plan to come in   Hyderabad for Meet Peehu Sinha and fix meeting with her and complete your all   incomplete dreams from our top class Independent Hyderabad escorts model. www.peehusinha.com

**Comment by hellais** [comment]
To prevent further €sC0rt spam, I am going to edit the comment of @kaerumy to not include the trigger keyword.

**Comment by nancychopra1** [comment]
I liked it so great and very interesting, also! Thanks for sharing the knowledge. Brilliant post, great tips and advice. 

http://www.nancychopra.net/
--

**Comment by avanimathur69** [comment]
Interesting story by you Thanks for shared. it is very useful of people's.
http://www.avaniseth.com/

**Comment by hellais** [comment]
I am going to lock this conversation due to there being too much spam. If you have further country blocklists to add, please file a separate ticket.

**Comment by hellais** [comment]
It's unclear to me how this issue is actionable. I am going to close it in favour of a more broader discussion to be done as part of: https://github.com/citizenlab/test-lists/issues/480
