### ISSUE TITLE
Test list for North Korea(kp)?

### ISSUE THREAD

**Issue by yanderemoe** [citizenlab/test-lists#182]
seems like Instagram is blocked in DPRK
https://news.vice.com/article/north-korea-has-blocked-instagram

**Comment by willscott** [comment]
Instagram is not blocked on any subnet I'm aware of, although it was temporarily disrupted for specific users at one point.

See, e.g. https://www.instagram.com/erictalmadge/ for posts from pyongyang from the past week.

Youtube has been blocked somewhat more widely as a bandwidth saving measure, but again on specific networks and it's hard to determine if there are any country-wide policies in place.

**Comment by hellais** [comment]
Please open a PR if you would like to contribute new URLs to the South Korea test list.
