### ISSUE TITLE
Write text for the URL submission wizard

### ISSUE THREAD

**Issue by hellais** [citizenlab/test-lists#19]
We should describe the workflow of the URL submission wizard as well as the text to be presented on the various steps.

@jakubd @mobilesuit do you have access to the @citizenlab spreadsheets used to build the original lists? If so you should add the content of them into here.

**Comment by jakubd** [comment]
@sneft would be the best for this.

**Comment by sneft** [comment]
I have the text descriptions of the content categories. I used many of them as the starting point for the proposed new content category codes found here:
https://github.com/citizenlab/test-lists/blob/master/lists/00-proposed-category_codes.csv

**Comment by hellais** [comment]
I think we should re-evaluate if a submission wizard is in fact the best solution to this problem before going ahead with writing copy.

I am closing this ticket and we can perhaps have a test-list roadmap discussion at CLSI.
