### ISSUE TITLE
Add "safety" column to the test-lists

### ISSUE THREAD

**Issue by hellais** [citizenlab/test-lists#22]
Add tags to URLs for Safe/Not safe or an extra column that provides a level of safety for that certain URL.

It was suggested by @josswright that we could also do this in an automated way by prompting the user before doing a scan "Do you feel safe testing these URLs":

```
URL 1 - yes/no
URL 2 - yes/no
etc.
```

This user feedback can then be submitted to us in a safe way and used to defined a metric of safety or perceived safety (perhaps even on a country by country basis).

**Comment by josswright** [comment]
A few aspects to this:

* This will be problematic with large test lists. It may be worth selecting a manageable subset of the URLs to be presented. If you are going to have some kind of voting/scoring feedback element then you should consider if it's worth presenting 'scary' URLs for user verification with higher probability.

* The URL itself will often be insufficient, as many URLs (such as grindr.com) will not be descriptive enough for a user to judge them. URL and category is probably a reasonable tradeoff, as URL and description is going to be too much work.

* On that note, which is probably mentioned elsewhere, there should also be a category-based opt-in for subsets of the test lists. Defining those categories appropriately will be a challenge.

**Comment by hellais** [comment]
In OONI probe we have gone for the suggestion that @josswright brought up here. Users are able to opt-in, opt-out of testing for particular categories.

I am closing this.
