### ISSUE TITLE
Add documentation on usage of bin/*

### ISSUE THREAD

**Issue by hellais** [citizenlab/test-lists#24]
Currently the README does not explain how to use the code in this repository to update the URL lists nor how to add new URLs.

**Comment by agrabeli** [comment]
There's now documentation (on the main OONI website) that explains how to contribute to test lists (and add URLs): https://ooni.torproject.org/get-involved/contribute-test-lists/ 

@hellais I thought we were going to drop the automatic updating of test lists (based on the script)? I might be confused though.

**Comment by hellais** [comment]
Yes I think we should remove the scripts from this repo and have it only contain data. In the future the alternative way would be supporting some app to submit URLs via a web frontend.

**Comment by hellais** [comment]
Bin does not exist anymore. Closing.
