### ISSUE TITLE
hdl.handle.net is blocked in Iran, not sure how to categorize

### ISSUE THREAD

**Issue by alanorth** [citizenlab/test-lists#322]
Handle.net is a provider of persistent URLs and is commonly used for institutional repositories (similar to DOIs). I am the administrator of a large open access repository of agricultural outputs and we recently noticed that the Handles do not work in Iran.

Here is an example of a persistent Handle link to an item on our repository: http://hdl.handle.net/10568/91553

I would submit a pull request with the URL in the Iran country list, but I'm not sure what to classify it as.

**Comment by willscott** [comment]
I'd use SRCH, since it acts as a portal / index linking out to a bunch of different content.
