### ISSUE TITLE
Move Gay Star News to global list?

### ISSUE THREAD

**Issue by kaerumy** [citizenlab/test-lists#349]
http://www.gaystarnews.com/,LGBT,LGBT,2017-10-15,citizenlab,

Noticed that this UK site providing global news is duplicated across several countries, and needs to be added in my.csv list where it is blocked.

Probably better to remove from country lists and move to global.csv?

**Comment by hellais** [comment]
It has been moved to the global test list. Closing: https://github.com/citizenlab/test-lists/blob/master/lists/global.csv#L1206
