### ISSUE TITLE
List of country codes with no test-list

### ISSUE THREAD

**Issue by anadahz** [citizenlab/test-lists#479]
There are a number of countries that have no test-list, help us to reduce improve the availability of country specific test-list.

Below the list of the country codes ([ISO 3166 alpha2](https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-country_codes.csv)) that have no test-list:

- [ ] AD (Andorra)
- [ ] AG (Antigua & Barbuda)
- [ ] AI (Anguilla)
- [ ] AN (Netherlands Antilles)
- [ ] AQ (Antarctica)
- [ ] AS (American Samoa)
- [ ] AW (Aruba)
- [ ] BB (Barbados)
- [ ] BF (Burkina Faso)
- [ ] BJ (Benin)
- [ ] BM (Bermuda)
- [ ] BN (Brunei Darussalam)
- [ ] BS (Bahama)
- [ ] BT (Bhutan)
- [ ] BU (Burma (no longer exists))
- [ ] BV (Bouvet Island)
- [ ] BW (Botswana)
- [ ] BZ (Belize)
- [ ] CC (Cocos (Keeling) Islands)
- [ ] CF (Central African Republic)
- [ ] CG (Congo)
- [ ] CI (Côte D'ivoire (Ivory Coast))
- [ ] CK (Cook Iislands)
- [ ] CS (Czechoslovakia (no longer exists))
- [ ] CV (Cape Verde)
- [ ] CX (Christmas Island)
- [ ] DD (German Democratic Republic (no longer exists))
- [ ] DJ (Djibouti)
- [ ] DM (Dominica)
- [ ] EH (Western Sahara)
- [ ] FJ (Fiji)
- [ ] FK (Falkland Islands (Malvinas))
- [ ] FM (Micronesia)
- [ ] FO (Faroe Islands)
- [ ] FX (France, Metropolitan)
- [ ] GD (Grenada)
- [ ] GF (French Guiana)
- [ ] GI (Gibraltar)
- [ ] GL (Greenland)
- [ ] GN (Guinea)
- [ ] GP (Guadeloupe)
- [ ] GQ (Equatorial Guinea)
- [ ] GS (South Georgia and the South Sandwich Islands)
- [ ] GU (Guam)
- [ ] GW (Guinea-Bissau)
- [ ] HM (Heard & McDonald Islands)
- [ ] HT (Haiti)
- [ ] IO (British Indian Ocean Territory)
- [ ] JM (Jamaica)
- [ ] KI (Kiribati)
- [ ] KM (Comoros)
- [ ] KN (St. Kitts and Nevis)
- [ ] KP (Korea, Democratic People's Republic of)
- [ ] KY (Cayman Islands)
- [ ] LA (Lao People's Democratic Republic)
- [ ] LC (Saint Lucia)
- [ ] LI (Liechtenstein)
- [ ] LR (Liberia)
- [ ] LU (Luxembourg)
- [ ] MC (Monaco)
- [ ] MG (Madagascar)
- [ ] MH (Marshall Islands)
- [ ] MO (Macau)
- [ ] MP (Northern Mariana Islands)
- [ ] MQ (Martinique)
- [ ] MS (Monserrat)
- [ ] MT (Malta)
- [ ] MU (Mauritius)
- [ ] MV (Maldives)
- [ ] MW (Malawi)
- [ ] NA (Namibia)
- [ ] NC (New Caledonia)
- [ ] NE (Niger)
- [ ] NR (Nauru)
- [ ] NT (Neutral Zone (no longer exists))
- [ ] NU (Niue)
- [ ] PF (French Polynesia)
- [ ] PG (Papua New Guinea)
- [ ] PM (St. Pierre & Miquelon)
- [ ] PN (Pitcairn)
- [ ] PW (Palau)
- [ ] RE (Réunion)
- [ ] SB (Solomon Islands)
- [ ] SC (Seychelles)
- [ ] SH (St. Helena)
- [ ] SJ (Svalbard & Jan Mayen Islands)
- [ ] SM (San Marino)
- [ ] SR (Suriname)
- [ ] ST (Sao Tome & Principe)
- [ ] SU (Union of Soviet Socialist Republics (no longer exists))
- [ ] SZ (Swaziland)
- [ ] TC (Turks & Caicos Islands)
- [ ] TF (French Southern Territories)
- [ ] TG (Togo)
- [ ] TK (Tokelau)
- [ ] TO (Tonga)
- [ ] TP (East Timor)
- [ ] TT (Trinidad & Tobago)
- [ ] TV (Tuvalu)
- [ ] UM (United States Minor Outlying Islands)
- [ ] VA (Vatican City State (Holy See))
- [ ] VC (St. Vincent & the Grenadines)
- [ ] VG (British Virgin Islands)
- [ ] VI (United States Virgin Islands)
- [ ] VU (Vanuatu)
- [ ] WF (Wallis & Futuna Islands)
- [ ] WS (Samoa)
- [ ] YD (Democratic Yemen (no longer exists))
- [ ] YT (Mayotte)
- [ ] YU (Yugoslavia)
- [ ] ZR (Zaire)

Feel free to mark this issue with the tag `help wanted`.

**Comment by hellais** [comment]
I updated the issue to sort them by name and added the country name next to it. It's probably going to be useful to prioritise these by importance though.

**Comment by Ogala** [comment]
@hellais  **Zaire (ZR)** is now the **Democratic Republic of Congo (CD)**

**Comment by hellais** [comment]
@Ogala thanks for the heads up, I just wrote a script to resolve the list names originally proposed by @anadahz into a country name, but did not look into how they were generated. In fact we already have a test list for DRC, in here: https://github.com/citizenlab/test-lists/blob/master/lists/cd.csv.

**Comment by hellais** [comment]
It's not clear to me how this issue is actionable and what value it's adding beyond what a person can already script themselves (if they care to do this type of work).

For example in the list above there are countries for which I would argue there is questionable value in having a test list for, an example is  AQ (Antarctica).

I am therefore going to close this issue and suggest we rather open one once we have a more clear idea of the priorities needed in test list creation.

**Comment by anadahz** [comment]
> There are a number of countries that have no test-list, help us to reduce improve the availability of country specific test-list.

The main objective of this issue is to create test-lists for the countries that do not have one.

There is no need to argue if a country's test-list is more valuable than another. Network interference is unfortunately a universal phenomenon.
