### ISSUE TITLE
add archive.is

### ISSUE THREAD

**Issue by xhdix** [citizenlab/test-lists#493]
In some Iranian ISPs, the "archive.is" address is censored.
Should it be added to `global.csv` or `ir.csv`? @hellais 
![image](https://user-images.githubusercontent.com/12384263/63080980-1eb2d680-bf4b-11e9-8f26-7af20cd74db0.png)
![image](https://user-images.githubusercontent.com/12384263/63081343-0e4f2b80-bf4c-11e9-8b56-adcc96b24389.png)
![image](https://user-images.githubusercontent.com/12384263/63081015-368a5a80-bf4b-11e9-98b8-cc2e9e380756.png)
![image](https://user-images.githubusercontent.com/12384263/63081046-49049400-bf4b-11e9-85a5-619697e7bffe.png)

**Comment by hellais** [comment]
I suggest adding it to the global list as it's one of the alexa top 10k most visited sites in the world.
