### ISSUE TITLE
using or not www

### ISSUE THREAD

**Issue by cguerrave** [citizenlab/test-lists#58]
Hello!

I'm working in a huge revamp of the venezuelan list and i'm a little bit confused in what to do with sites that support www. because in some lists we have sites with, others without and others with both. Which approach do you recommend for this repo? 

I am almost ready to upload the new list but this is stopping me.

Thank you very much!

**Comment by hellais** [comment]
Hi @cguerrave thanks for this!

I think that the general rule should be to use the `www` prefix only when a request to `http://example.com` does a 30x redirect to `http://www.example.com`.

In other cases I would use the URL without the `www` prefix.

**Comment by cguerrave** [comment]
Thanks for the help :) @hellais

**Comment by Harpy074** [comment]
@hellais is there a way to flag this kind of problem automatically in the future?
![image](https://user-images.githubusercontent.com/88121480/135449785-475431dd-e6e5-4464-bef2-20ea8aa32311.png)
_(Photo above came from global.csv and photo below came from bi.csv)_
![image](https://user-images.githubusercontent.com/88121480/135449887-f15c2923-a655-45d8-8cf5-f32371343e11.png)
