### ISSUE TITLE
Discuss possibility of including application specific addresses

### ISSUE THREAD

**Issue by hellais** [citizenlab/test-lists#6]
There are some cases where we want to have lists of some addresses (or strings) that are used specifically in the context of some application.

I believe the most logical place to put these is inside of a dedicated "global" list, but it should be placed in the context of the software using it.

Here are some examples of the sorts of addresses I am talking about:
- The pluggable transport addresses (and in some cases shared secrets or hash fingerprints) of the Tor bridges shipped as part of Tor Browser Bundle release X
- The IP and ports (and possibly fingerprints) or Tor directory authorities that are used for discovery of the Tor network by "vanilla" tor (country that block access to the Tor network will block these, but may not be blocking also the bridges)
- The list of IP and ports used by a $INSERT_POPULAR_INTERNET_CHAT_APP application (I'm thinking whatsapp, viber, etc.)
- The list of IP, port and protocol by the various VPN providers (it can be useful to check if these are being blocked)
- List of IPs of open DNS resolvers per country

I think you get an idea of the sorts of data I am talking about.

I would propose we create the following new directory structure:

```
lists
├── services
│   ├── tor
│   │   ├── bridges.csv
│   │   └── directory_authorities.csv
│   └── vpn
etc.
```

Each service specific namespace can have it's own format, maintaing some common elements such as: `name`, `date_added`, `data_format_version`, `source`, `notes`.

@sneft, @chokepoint-project, @mobilesuit, @jakubd what do you think?

**Comment by sneft** [comment]
I think this is a great idea. @jakubd has actually already compiled such a list for chat apps. Once we clean the list up we'll post it here.

**Comment by chokepoint-project** [comment]
@arturo

Yes, that would be great. There are a number of list sets you propose
that would require active probing (such as open resolvers.) We're
working on some of these at the moment : http://api.diid.co/ (very
experimental, mileage may vary.)

**Comment by hellais** [comment]
@chokepoint-project oh wow very interesting.

I am writing I tiny framework to support adding third party resource parsing and updating of the services. How I imagine this to work is that for each service we want to support you write a little bit of code to 1) Obtain the data from the third party source 2) Parse it in the format expected by test-lists.
Not sure when it will be complete, but it's good to know there is interest in this.

BTW, a lot of us OONI people hang around on IRC at irc.oftc.net on the channel #ooni. If you join there we can perhaps discuss some aspects of this more realtime.

**Comment by hellais** [comment]
@sneft I did a bit more work on feature branch #9 including the ability of adding government specific blocklists.

For the moment I added some official blocklists from the Italian government, one is scraped from a censorship observatory project run by BOFH. They basically collect all the block notices from the italian government and post them online.

The second is directly from the website of AAMS the state monopoly for gambling and contains only gambling sites.

**Comment by hellais** [comment]
No discussions have happened in relation to this in 5 years, so I think this is currently out of scope for this repo. At OONI we track these inside of files that are part of the software components which uses it.

I don't think adding more things into the test-list repo is a good idea. I am going for the time being close this issue, but feel free to make a new one if you are particularly passionate about this.
