### ISSUE TITLE
New domains censored by China

### ISSUE THREAD

**Issue by happywhitelake** [citizenlab/test-lists#683]
Please consider adding the following notable domains into the CN list as I recently found that they are censored in China by DNS poisoning.

Congressional-Executive Commission on China: `cecc.gov`
United States Commission on International Religious Freedom: `uscirf.gov`
Tracking the United States Congress: `govtrack.us`
The Wire India: `thewire.in`

**Comment by agrabeli** [comment]
Thank you @phongiswindy ! I have opened a pull request with these URLs here: https://github.com/citizenlab/test-lists/pull/684

**Comment by hellais** [comment]
This is done.
