### ISSUE TITLE
These are blocked in BD

### ISSUE THREAD

**Issue by Oymate** [citizenlab/test-lists#790]
https://vk.com
https://medium.com (previously, now not blocked)
https://bit.ly
https://archive.org
https://issuu.com
https://mediafire.com
https://change.org
https://lookeast.in

**Comment by Oymate** [comment]
@agrabeli

**Comment by mhombach** [comment]
And what is this issue about? If you want to add those sites to the check list, create a PR for them :)

**Comment by mhombach** [comment]
@Oymate  If you are not interested in having those entries in the global list anymore, please close this issue :)

**Comment by Oymate** [comment]
No response on what's wrong: https://github.com/citizenlab/test-lists/pull/809

**Comment by RandomGuy48** [comment]
@Oymate vk.com, issuu.com and lookeast.in are already in the [bd.csv](https://github.com/citizenlab/test-lists/blob/master/lists/bd.csv) while the remaining URLs you mentioned are already at [global.csv](https://github.com/citizenlab/test-lists/blob/master/lists/global.csv)

I think this issue should be closed.
