### ISSUE TITLE
Much more is missing from List.

### ISSUE THREAD

**Issue by zaheercena** [citizenlab/test-lists#81]
Pakistan Blocked much more websites and links. If only these you tested is fine but if this is Total blocked URL list then I can add much more.

**Comment by agrabeli** [comment]
@zaheercena thanks for your message, and apologies for the late reply. We'd love to include additional URLs in the Pakistani test list. Please add them to the list (https://github.com/citizenlab/test-lists/blob/master/lists/pk.csv) with a pull request, or feel free to share them here and I'll add them for you.

**Comment by hellais** [comment]
If you want to contribute some URLs please open a PR
