### ISSUE TITLE
Initial new list for Cambodia kh.csv

### ISSUE THREAD

**Issue by kaerumy** [citizenlab/test-lists#83]
url,category_code,category_description,date_added,source,notes
https://www.cambodiadaily.com/,NEWS,News and media,2016-09-17,cchr,Indepdenent online news website
http://khmer.voanews.com/,NEWS,News,2016-09-17,cchr,Indepdenent online news website
http://cchrcambodia.org/,HUMR,Human Rights,2016-09-17,cchr,Human Rights Organization
http://www.cpp.org.kh/,POLR,Political Party,2016-09-17,,cchr,Current ruling political party

**Comment by agrabeli** [comment]
@kaerumy thanks a million for providing these URLs to get started with a new test list for Cambodia! :) I've added more URLs to the test list & have made a pull request (https://github.com/citizenlab/test-lists/pull/89).

**Comment by sneft** [comment]
Thanks for the contribution! I've merged the pull request (#89) so I'm closing.
