### ISSUE TITLE
Can source be anon?

### ISSUE THREAD

**Issue by kaerumy** [citizenlab/test-lists#84]
We have a request from a country partner, that wishes to not be credited as direct source due to the sensitive nature of some of the urls.

Should we put the source as anon? Or should an intermediary that is not at risk such as sinarproject or ooni be put in there instead?

Regards

**Comment by sneft** [comment]
Yes, we're happy to accept submissions from sources who wish to remain anonymous. Adding "anon" in the source field is fine.
