### ISSUE TITLE
Looks like Friendster website is closed forever

### ISSUE THREAD

**Issue by Vort** [citizenlab/test-lists#871]
Probably not needed anymore.

https://en.wikipedia.org/wiki/Friendster

_"Three years later, on June 30, 2018 it closed down as a company and eventually dissolved."_

https://github.com/citizenlab/test-lists/blob/7b381fe04825fcfd8329415e9a405da9ff140cf5/lists/global.csv#L563

**Comment by RandomGuy48** [comment]
@Vort yeah I actually made a pull request about it: #840 
They removed it now. I think this issue should be closed.
