### ISSUE TITLE
How to deal with blocked cloud service DNS?

### ISSUE THREAD

**Issue by kaerumy** [citizenlab/test-lists#95]
Sarawak Report uses AWS auto assigned DNS for cloud host servers as a way to temporarily overcome DNS blocks on their main server. These addresses eventually get added to Malaysia's official block lists.

What's best way of tracking these domains? Should we add them to my.csv country lists too?

http://digimon.sinarproject.org/incidents/sarawak-report

**Comment by sneft** [comment]
Yes, I think it would be reasonable to include those domains. Given that their purpose might not be obvious at first glance, I recommend use the 'notes' field of the testing list to explain in more detail.

**Comment by kaerumy** [comment]
OK thanks, added with pull request https://github.com/citizenlab/test-lists/pull/113
