### ISSUE TITLE
Remove all *.gov.br from br.csv list

### ISSUE THREAD

**Issue by gusgustavo** [citizenlab/test-lists#986]
It's very unlikely that the Brazilian gov or even another gov in the region would block these websites.

I removed all `.gov.br ` websites in this PR: https://github.com/citizenlab/test-lists/pull/985

**Comment by xhdix** [comment]
test-list is not block-list
ICYMI:
https://www.youtube.com/watch?v=XKWGS2VvEAs

https://www.youtube.com/watch?v=-1kkd_xuXQs

**Comment by gusgustavo** [comment]
It's not just about blocking/non-blocking, but I've checked other countries lists and it's seems very unreasonable to have 1.500 websites from the government.

a. Brazilians are testing more '.gov.br' websites than any other category. 
b. 1.5k gov.br websites is just too much. It's hard to manage and update such large test list.

**Comment by xhdix** [comment]
a. if that's the case, there is a problem in the OONI's prioritization algorithm.
b. I agree. max 20 is enough for `.gov.br` websites. but not all of them.
